# This is a config for E2B sandbox template.
# You can use 'template_id' (h2uk89oim5lyy7sc0pou) or 'template_name (gitwit-streamlit) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='gitwit-streamlit')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'gitwit-streamlit' })

team_id = "34eab90a-97dc-4be5-87e3-a17b6e6e8bc6"
dockerfile = "e2b.Dockerfile"
template_name = "gitwit-streamlit"
template_id = "h2uk89oim5lyy7sc0pou"
